import { HomeworkSubmission } from '../types';

export const homeworkSubmissions: HomeworkSubmission[] = [
  {
    id: 'submission-1',
    filename: 'physics_homework_week3.pdf',
    createdAt: '2023-11-15T14:32:45Z',
    status: 'verified',
    feedback: 'Verified as handwritten. Good job on your Newton\'s Laws assignment!',
    aiGenerated: false
  },
  {
    id: 'submission-2',
    filename: 'chemistry_assignment.pdf',
    createdAt: '2023-11-10T09:15:22Z',
    status: 'rejected',
    feedback: 'Our AI detected that this homework was generated by AI. Please submit handwritten work.',
    aiGenerated: true
  },
  {
    id: 'submission-3',
    filename: 'biology_lab_report.pdf',
    createdAt: '2023-11-05T16:48:33Z',
    status: 'verified',
    feedback: 'Verified as handwritten. Excellent detailed observations in your lab report.',
    aiGenerated: false
  }
];